[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 20

[[main]]
  name = "News"
  url = "#posts"
  weight = 30

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[main]]
  identifier = "activities-menu"
  url = "activities"
  name = "Activities"
  weight = 50
  has_children = true

[[main]]
  parent = "activities-menu"
  name = "Professional Activities"
  url = "activities/#activities"

[[main]]
parent = "activities-menu"
name = "Teaching"
url = "activities/#teaching"

[[main]]
  name = "About"
  url = "about/"
  weight = 60
   
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
